sudo pacman -S --noconfirm --needed \
  1password-beta \
  1password-cli \
  alacritty \
  arch-install-scripts \
  avahi \
  bash-completion \
  bat \
  bcc-tools \
  blueberry \
  brightnessctl \
  btrfs-progs \
  btop \
  cargo \
  cfdisk \
  clang \
  clickhouse \
  cmake \
  cups \
  cups-browsed \
  cups-filters \
  cups-pdf \
  docker \
  docker-buildx \
  docker-compose \
  dosfstools \
  distrobox \
  dust \
  e2fsprogs \
  evince \
  eza \
  fastfetch \
  fcitx5 \
  fcitx5-gtk \
  fcitx5-qt \
  fd \
  ffmpegthumbnailer \
  firefox \
  flatpak \
  fzf \
  gcc14 \
  git-delta \
  gparted \
  gptfdisk \
  github-cli \
  gnome-calculator \
  gnome-keyring \
  gnome-themes-extra \
  gum \
  gvfs-mtp \
  hypridle \
  hyprland \
  hyprland-qtutils \
  hyprlock \
  hyprpicker \
  hyprshot \
  hyprsunset \
  imagemagick \
  impala \
  imv \
  inetutils \
  jq \
  just \
  kdenlive \
  kubectl \
  kubernetes \
  kvantum-qt5 \
  lazydocker \
  lazygit \
  less \
  libqalculate \
  libreoffice \
  llvm \
  localsend \
  luarocks \
  lynx \
  mako \
  man \
  mariadb-libs \
  meson \
  mise \
  msedit \
  mpv \
  nautilus \
  neovim \
  nodejs \
  npm \
  noto-fonts \
  noto-fonts-cjk \
  noto-fonts-emoji \
  noto-fonts-extra \
  nss-mdns \
  nvim \
  obs-studio \
  obsidian \
  onnxruntime \
  osvmarchi-chromium \
  pamixer \
#  pinta \
  playerctl \
  plocate \
  perf \
  pkgconf \
  plymouth \
  podman \
  protobuf \
  polkit-gnome \
  postgresql-libs \
  power-profiles-daemon \
  python-gobject \
  python-poetry-core \
  python-terminaltexteffects \
  python-transformers \
  ripgrep \
  rocksdb \
  rust \
  rust-analyzer \
  satty \
  signal-desktop \
  slurp \
  spotify \
  starship \
  sushi \
  swaybg \
  swayosd \
  system-config-printer \
  tesseract \
  tldr \
  tokei \
  tree-sitter-cli \
  ttf-cascadia-mono-nerd \
  ttf-jetbrains-mono \
  typora \
#  tzupdate \
  ufw \
  ufw-docker \
  unzip \
  uwsm \
  virt-manager \
  vscode \
  walker-bin \
  waybar \
  wf-recorder \
  whois \
  wiremix \
  wireplumber \
  wl-clip-persist \
  wl-clipboard \
  wl-screenrec \
  woff2-font-awesome \
  xdg-desktop-portal-gtk \
  xdg-desktop-portal-hyprland \
  xmlstarlet \
  xournalpp \
#  yaru-icon-theme \
  yay \
  zellij \
  zoxide
